package pkg.schema.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-10-19T14:06:21.600-04:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "FahrenheitToCelsius")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "")
        java.lang.String fahrenheit
    );

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "CelsiusToFahrenheit")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "")
        java.lang.String celsius
    );
}
